// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zrzxctlcqloeodgazjyl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpyenhjdGxjcWxvZW9kZ2F6anlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNDkxNzEsImV4cCI6MjA3MzkyNTE3MX0.ugcEVfZ_P5jJZrpaNEPZ_KASnl75H0f9cEaix9hGrYI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});